FROM node:20-alpine as build
WORKDIR /app
#Q- Copy all the source code to above workdir
COPY . .
#Q- Write down the command to install package dependency (npm install) 
RUN npm install
#Q- Write down the command to create project build (npm run build)
RUN npm run build

FROM nginx:1.23.4-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
#Q- Nginx uses default port 80 whhich command I should write to expose 80 port in this dockerfile 
EXPOSE 80
CMD [ "nginx" , "-g" , "daemon off;" ]